repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: demotwo
  description: another demo
  author: Glebus
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
