contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #demotwo channel"
    url: https://nfcore.slack.com/channels/demotwo
    about: Discussion about the nf-core/demotwo pipeline
